spring.application.name=01quick-start

# deepseek
spring.ai.deepseek.api-key=${DEEP_SEEK_KEY}
spring.ai.deepseek.chat.options.model=deepseek-reasoner

# 阿里云百炼
spring.ai.dashscope.api-key=${ALI_AI_KEY} 
spring.ai.dashscope.chat.options.model=qwen3.7-max

# ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3.5:0.8b
