spring.application.name=09rag

spring.ai.dashscope.api-key=${ALI_AI_KEY}
spring.ai.dashscope.chat.options.model=deepseek-v4-flash-0731

spring.ai.dashscope.embedding.options.model=qwen3.7-text-embedding
#spring.ai.dashscope.embedding.options.dimensions=
