spring.application.name=06flight-booking

spring.ai.dashscope.api-key=${ALI_AI_KEY}
spring.ai.dashscope.chat.options.model=deepseek-v4-flash-0731

logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=debug

spring.ai.mcp.client.request-timeout=20s
# 第一种方式：将配置单独放到json文件中
#spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers-config.json
# 第二种方式：将配置直接放到全局配置文件中
spring.ai.mcp.client.stdio.connections.gaode-map.command=cmd
spring.ai.mcp.client.stdio.connections.gaode-map.args=/c,npx,-y,@baidumap/mcp-server-baidu-map
spring.ai.mcp.client.stdio.connections.gaode-map.env.BAIDU_MAP_API_KEY=OLW8CzE17OmVpTQy93Yi4UHnxycbzc5R

logging.level.io.modelcontextprotocol.client:debug
logging.level.io.modelcontextprotocol.spec:debug

